all: TempConversion TempConversion2

TempConversion: TempConversion.cpp
	g++ -Wall -g TempConversion.cpp -o TempConversion

TempConversion2: TempConversion2.cpp
	g++ -Wall -g TempConversion2.cpp -o TempConversion2
