all: mystery backward count file comment WithoutComment

mystery: mystery.cpp
	g++ -Wall -g mystery.cpp -o mystery

backward: backward.cpp
	g++ -Wall -g backward.cpp -o backward

count: count.cpp
	g++ -Wall -g count.cpp -o count

comment: comment.cpp
	g++ -Wall -g comment.cpp -o comment

WithoutComment: WithoutComment.cpp
	g++ -Wall -g WithoutComment.cpp -o WithoutComment

file: file.cpp
	g++ -Wall -g file.cpp -o file
